SET IDENTITY_INSERT [dbo].[Brands] ON
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (1, N'Laptop Acer', 1)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (2, N'Laptop Asus', 1)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (3, N'Laptop Lenovo', 1)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (4, N'Laptop MSI', 1)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (5, N'Laptop HP', 1)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (7, N'PC Gaming', 2)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (8, N'PC Văn Phòng', 2)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (9, N'PC Đồ Họa', 2)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (10, N'Màn Hình Acer', 3)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (11, N'Màn Hình Asus', 3)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (12, N'Màn Hình MSI', 3)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (13, N'Màn Hình Samsung', 3)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (14, N'Màn Hình Philips', 3)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (15, N'Bàn Phím Asus', 4)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (16, N'Bàn Phím Logitech', 4)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (17, N'Bàn Phím Razer', 4)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (18, N'Chuột Asus', 5)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (19, N'Chuột Logitech', 5)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (20, N'Chuột Razer', 5)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (21, N'Tai Nghe Asus', 6)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (22, N'Tai Nghe Logitech', 6)
INSERT INTO [dbo].[Brands] ([brandID], [brandName], [categoryID]) VALUES (23, N'Tai Nghe Razer', 6)
SET IDENTITY_INSERT [dbo].[Brands] OFF
